//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SectorHUDgui.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SectorHUDgui.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Apply ähnelt.
        /// </summary>
        internal static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Configuration has been updated. Start the monitor again if necessary. ähnelt.
        /// </summary>
        internal static string ConfigurationHasBeenUpdated {
            get {
                return ResourceManager.GetString("ConfigurationHasBeenUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Are you sure that you want to reset the configuration to the default values? ähnelt.
        /// </summary>
        internal static string ConfirmReset {
            get {
                return ResourceManager.GetString("ConfirmReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Connected with Telemetry server ähnelt.
        /// </summary>
        internal static string ConnectedWithTelemetryServer {
            get {
                return ResourceManager.GetString("ConnectedWithTelemetryServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Database ähnelt.
        /// </summary>
        internal static string Database {
            get {
                return ResourceManager.GetString("Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Demo ähnelt.
        /// </summary>
        internal static string Demo {
            get {
                return ResourceManager.GetString("Demo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Demo mode active – click Demo again to stop ähnelt.
        /// </summary>
        internal static string DemoActive {
            get {
                return ResourceManager.GetString("DemoActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Demo data showed ähnelt.
        /// </summary>
        internal static string DemoDataDisplayed {
            get {
                return ResourceManager.GetString("DemoDataDisplayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Demo mode stopped ähnelt.
        /// </summary>
        internal static string DemoStopped {
            get {
                return ResourceManager.GetString("DemoStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Active Mods ähnelt.
        /// </summary>
        internal static string DisplayActiveMods {
            get {
                return ResourceManager.GetString("DisplayActiveMods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Time (real):          {0} ähnelt.
        /// </summary>
        internal static string DisplayClock {
            get {
                return ResourceManager.GetString("DisplayClock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Destination:          {0} ähnelt.
        /// </summary>
        internal static string DisplayDestination {
            get {
                return ResourceManager.GetString("DisplayDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Distance:             {0} {1} ähnelt.
        /// </summary>
        internal static string DisplayDistance {
            get {
                return ResourceManager.GetString("DisplayDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Travel time (game):   {0} h ähnelt.
        /// </summary>
        internal static string DisplayETARel {
            get {
                return ResourceManager.GetString("DisplayETARel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Travel time (real):   {0} min ähnelt.
        /// </summary>
        internal static string DisplayETARelRT {
            get {
                return ResourceManager.GetString("DisplayETARelRT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Arrival time (real):  {0} ähnelt.
        /// </summary>
        internal static string DisplayETART {
            get {
                return ResourceManager.GetString("DisplayETART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Game:                 {0} ähnelt.
        /// </summary>
        internal static string DisplayGame {
            get {
                return ResourceManager.GetString("DisplayGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die General Information ähnelt.
        /// </summary>
        internal static string DisplayGeneralInformation {
            get {
                return ResourceManager.GetString("DisplayGeneralInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Job Information ähnelt.
        /// </summary>
        internal static string DisplayJobInformation {
            get {
                return ResourceManager.GetString("DisplayJobInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Time left (game):     {0} h ähnelt.
        /// </summary>
        internal static string DisplayRemRel {
            get {
                return ResourceManager.GetString("DisplayRemRel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Time left (real):     {0} min ähnelt.
        /// </summary>
        internal static string DisplayRemRelRT {
            get {
                return ResourceManager.GetString("DisplayRemRelRT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deadline (real):      {0} ähnelt.
        /// </summary>
        internal static string DisplayRemRT {
            get {
                return ResourceManager.GetString("DisplayRemRT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sector:               {0} ähnelt.
        /// </summary>
        internal static string DisplaySector {
            get {
                return ResourceManager.GetString("DisplaySector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Origin:               {0} ähnelt.
        /// </summary>
        internal static string DisplaySource {
            get {
                return ResourceManager.GetString("DisplaySource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DLC file not found: {0} (skipped) ähnelt.
        /// </summary>
        internal static string DlcFileNotFound {
            get {
                return ResourceManager.GetString("DlcFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Done ähnelt.
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Done: {0} database updated, {1} sectors added ähnelt.
        /// </summary>
        internal static string DoneGameDatabaseUpdated {
            get {
                return ResourceManager.GetString("DoneGameDatabaseUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit Configuration ähnelt.
        /// </summary>
        internal static string EditConfiguration {
            get {
                return ResourceManager.GetString("EditConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter sector name (e.g., sec+0004-0002)
        ///or coordinates (e.g., 8520,-12650): ähnelt.
        /// </summary>
        internal static string EnterSectorName {
            get {
                return ResourceManager.GetString("EnterSectorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error: Telemetry server returned status code {0} ähnelt.
        /// </summary>
        internal static string ErrorTelemetryServer {
            get {
                return ResourceManager.GetString("ErrorTelemetryServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error while opening log file ähnelt.
        /// </summary>
        internal static string ErrorWhileOpeningLog {
            get {
                return ResourceManager.GetString("ErrorWhileOpeningLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error while opening the PDF file:
        ///{0} ähnelt.
        /// </summary>
        internal static string ErrorWhileOpeningPdf {
            get {
                return ResourceManager.GetString("ErrorWhileOpeningPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exit ähnelt.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SKZK Extractor not found in {0} ähnelt.
        /// </summary>
        internal static string ExtractorNotFound {
            get {
                return ResourceManager.GetString("ExtractorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to start telemetry server: {0} ähnelt.
        /// </summary>
        internal static string FailedToStartTelemetryServer {
            get {
                return ResourceManager.GetString("FailedToStartTelemetryServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File ähnelt.
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} database has been updated. ähnelt.
        /// </summary>
        internal static string GameDatabaseHasBeenUpdated {
            get {
                return ResourceManager.GetString("GameDatabaseHasBeenUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Info: Game is not connected to telemetry. ähnelt.
        /// </summary>
        internal static string GameIsNotConnectedToTelemetry {
            get {
                return ResourceManager.GetString("GameIsNotConnectedToTelemetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die game.log.txt not found in {0} ähnelt.
        /// </summary>
        internal static string GamelogNotFound {
            get {
                return ResourceManager.GetString("GamelogNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Help ähnelt.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die HTTP error while accessing Telemetry server ({0}): {1} {2} ähnelt.
        /// </summary>
        internal static string HttpErrorWhileAccessingTelemetryServer {
            get {
                return ResourceManager.GetString("HttpErrorWhileAccessingTelemetryServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Info ähnelt.
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Build date: {0:dd.MM.yyyy}
        /// ähnelt.
        /// </summary>
        internal static string InfoTextBuildDate {
            get {
                return ResourceManager.GetString("InfoTextBuildDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copyright © 2026  {0}
        ///Licensed under the GNU General Public License v2.0.
        ///This program is free software.
        ///
        ///Database: {1}
        ///Settings: {2}
        ///
        /// ähnelt.
        /// </summary>
        internal static string InfoTextCopyrightPaths {
            get {
                return ResourceManager.GetString("InfoTextCopyrightPaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Euro Truck Simulator 2: {0} Mods/DLCs, {1} Sectors
        ///American Truck Simulator: {2} Mods/DLCs, {3} Sectors ähnelt.
        /// </summary>
        internal static string InfoTextDatabase {
            get {
                return ResourceManager.GetString("InfoTextDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Version {0}.{1}.{2}
        ///  ähnelt.
        /// </summary>
        internal static string InfoTextVersion {
            get {
                return ResourceManager.GetString("InfoTextVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Instructions ähnelt.
        /// </summary>
        internal static string Instructions {
            get {
                return ResourceManager.GetString("Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid format. ähnelt.
        /// </summary>
        internal static string InvalidFormat {
            get {
                return ResourceManager.GetString("InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mod file not found: {0} (skipped) ähnelt.
        /// </summary>
        internal static string ModFileNotFound {
            get {
                return ResourceManager.GetString("ModFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Monitor ähnelt.
        /// </summary>
        internal static string Monitor {
            get {
                return ResourceManager.GetString("Monitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Monitor is running ähnelt.
        /// </summary>
        internal static string MonitorIsRunning {
            get {
                return ResourceManager.GetString("MonitorIsRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Monitor stopped ähnelt.
        /// </summary>
        internal static string MonitorStopped {
            get {
                return ResourceManager.GetString("MonitorStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New configuration file created. Please control paths and adjust if necessary. ähnelt.
        /// </summary>
        internal static string NewConfigurationFileCreated {
            get {
                return ResourceManager.GetString("NewConfigurationFileCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No active job ähnelt.
        /// </summary>
        internal static string NoActiveJob {
            get {
                return ResourceManager.GetString("NoActiveJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No connection - Is the game running? ähnelt.
        /// </summary>
        internal static string NoConnectionIsTheGameRunning {
            get {
                return ResourceManager.GetString("NoConnectionIsTheGameRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No mods found ähnelt.
        /// </summary>
        internal static string NoModsFound {
            get {
                return ResourceManager.GetString("NoModsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No mods found at this location. ähnelt.
        /// </summary>
        internal static string NoModsFoundAtThisLocation {
            get {
                return ResourceManager.GetString("NoModsFoundAtThisLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Program is already running. ähnelt.
        /// </summary>
        internal static string ProgramIsAlreadyRunning {
            get {
                return ResourceManager.GetString("ProgramIsAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Query ATS ähnelt.
        /// </summary>
        internal static string QueryATS {
            get {
                return ResourceManager.GetString("QueryATS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Query ETS2 ähnelt.
        /// </summary>
        internal static string QueryETS2 {
            get {
                return ResourceManager.GetString("QueryETS2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Query {0} ähnelt.
        /// </summary>
        internal static string QueryGame {
            get {
                return ResourceManager.GetString("QueryGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Querying database ({0}) for mods at sector ({1}, {2})... ähnelt.
        /// </summary>
        internal static string QueryingDatabaseSectortable {
            get {
                return ResourceManager.GetString("QueryingDatabaseSectortable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ready ähnelt.
        /// </summary>
        internal static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Recreate ATS ähnelt.
        /// </summary>
        internal static string RecreateATS {
            get {
                return ResourceManager.GetString("RecreateATS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Recreate ETS2 ähnelt.
        /// </summary>
        internal static string RecreateETS2 {
            get {
                return ResourceManager.GetString("RecreateETS2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reset ähnelt.
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Result ähnelt.
        /// </summary>
        internal static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [{0}%] Scanning {1}... ähnelt.
        /// </summary>
        internal static string ScanningMod {
            get {
                return ResourceManager.GetString("ScanningMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [{0}%] Deep scanning {1}... ähnelt.
        /// </summary>
        internal static string ScanningModDeep {
            get {
                return ResourceManager.GetString("ScanningModDeep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select file ähnelt.
        /// </summary>
        internal static string SelectFile {
            get {
                return ResourceManager.GetString("SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show log file ähnelt.
        /// </summary>
        internal static string ShowLog {
            get {
                return ResourceManager.GetString("ShowLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start ähnelt.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Starting telemetry server... ähnelt.
        /// </summary>
        internal static string StartingTelemetryServer {
            get {
                return ResourceManager.GetString("StartingTelemetryServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stop ähnelt.
        /// </summary>
        internal static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Telemetry server is already running. ähnelt.
        /// </summary>
        internal static string TelemetryServerIsAlreadyRunning {
            get {
                return ResourceManager.GetString("TelemetryServerIsAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Timeout while accessing Telemetry server ({0}): {1} ähnelt.
        /// </summary>
        internal static string TimeoutTelemetryServer {
            get {
                return ResourceManager.GetString("TimeoutTelemetryServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unexpected error while accessing Telemetry server ({0}): {1} ähnelt.
        /// </summary>
        internal static string UnexpectedErrorWhileAccessingTelemetryServer {
            get {
                return ResourceManager.GetString("UnexpectedErrorWhileAccessingTelemetryServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update ATS ähnelt.
        /// </summary>
        internal static string UpdateATS {
            get {
                return ResourceManager.GetString("UpdateATS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update ETS2 ähnelt.
        /// </summary>
        internal static string UpdateETS2 {
            get {
                return ResourceManager.GetString("UpdateETS2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Updating {0} database... ähnelt.
        /// </summary>
        internal static string UpdatingGameDatabase {
            get {
                return ResourceManager.GetString("UpdatingGameDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die waiting for game... ähnelt.
        /// </summary>
        internal static string WaitingForGame {
            get {
                return ResourceManager.GetString("WaitingForGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Warning ähnelt.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
